/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlsalontocnam;

import java.awt.Color;
//import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
//import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import java.util.Date;

/**
 *
 * @author Admin
 */
public class HoaDonJPanel extends javax.swing.JPanel {
    DefaultTableModel tabModel;
    /**
     * Creates new form HoaDonJPanel
     */
    public HoaDonJPanel() throws SQLException {
        initComponents();
         tabModel = (DefaultTableModel)tabHD.getModel();
        
        showHoadon();
    }

    private void showHoadon() throws SQLException{
        List<Hoa_don> hoadonList = null;
        try {
             hoadonList = Hoa_donDao.findAll();
        } catch (ClassNotFoundException ex) {
         Logger.getLogger(HoaDonJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        tabModel.setRowCount(0);
        
        hoadonList.forEach((hd) -> {
            tabModel.addRow(new Object[] {tabModel.getRowCount()+1, hd.getMahd(), hd.getMakh(), hd.getManv(), hd.getMadv(), hd.getTongtien(), hd.getNgaythanhtoan(), hd.getHinhthucthanhtoan() });
        });
    }
    private void LoadData() throws ClassNotFoundException, SQLException, ParseException
    {
        if (tabHD.getSelectedRow() != -1) {
            //-- Xác định hàng đã click
            int i = tabHD.getSelectedRow();
            
            //-- Lấy được danh sách sinh viên
            List<Hoa_don> lsthd = Hoa_donDao.findAll();
            //-- Xác định là dịch vụ nào đang được click
            
            Hoa_don hd = lsthd.get(i);
            //--- Set giá trị cho các control
            txtMahd.setText(hd.getMahd());
            txtMakh.setText(hd.getMakh());
                txtManv.setText(hd.getManv());
                txtMadv.setText(hd.getMadv());
                String tt=String.valueOf(hd.getTongtien());
                txtTongtien.setText(tt);
                SimpleDateFormat ngaytt= new SimpleDateFormat("yyyy-MM-dd");
                Date date= ngaytt.parse(hd.getNgaythanhtoan());
                dcNgaythanhtoan.setDate(date);
                cmbHinhttt.setSelectedItem(hd.getHinhthucthanhtoan());
        
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLammoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabHD = new javax.swing.JTable();
        txtMahd = new javax.swing.JTextField();
        txtMakh = new javax.swing.JTextField();
        txtManv = new javax.swing.JTextField();
        txtMadv = new javax.swing.JTextField();
        txtTongtien = new javax.swing.JTextField();
        cmbHinhttt = new javax.swing.JComboBox<>();
        dcNgaythanhtoan = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setText("Mã hóa đơn");

        jLabel2.setText("Mã khách hàng");

        jLabel3.setText("Mã nhân viên");

        jLabel4.setText("Mã dịch vụ");

        jLabel6.setText("Tổng tiền");

        jLabel7.setText("Ngày thanh toán");

        jLabel8.setText("Hình thức thanh toán");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-sua.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-lammoi.png"))); // NOI18N
        btnLammoi.setText("Làm mới");
        btnLammoi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-xoa.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-timkiem.png"))); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        tabHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã hóa đơn", "Mã khách hàng", "Mã nhân viên", "Mã dịch vụ", "Tổng tiền", "Ngày thanh toán", "Hình thức thanh toán"
            }
        ));
        tabHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabHD);
        if (tabHD.getColumnModel().getColumnCount() > 0) {
            tabHD.getColumnModel().getColumn(2).setResizable(false);
            tabHD.getColumnModel().getColumn(3).setResizable(false);
        }

        txtTongtien.setEnabled(false);

        cmbHinhttt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Thẻ tín dụng", "Thanh toán online" }));

        dcNgaythanhtoan.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMahd, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(txtMakh)
                            .addComponent(txtManv)
                            .addComponent(txtMadv))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcNgaythanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbHinhttt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(btnLammoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(dcNgaythanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(cmbHinhttt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMadv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
//        Date dtn= dcNgaythanhtoan.getDate();
//        DateFormat dateFormat= new SimpleDateFormat("yyyy-MM-dd");
         StringBuilder sb= new StringBuilder();
        if(txtMahd.getText().equals(""))
        {
            sb.append("Ma hoa don khong duoc de trong!!!");
            txtMahd.setBackground(Color.red);
        }
        else
            txtMahd.setBackground(Color.WHITE);
        if(sb.length()>0)
        {
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        try{
            Hoa_don hd= new Hoa_don();
            hd.setMahd(txtMahd.getText());
            hd.setMakh(txtMakh.getText());
            hd.setManv(txtManv.getText());
            hd.setMadv(txtMadv.getText());
            hd.setTongtien(Float.parseFloat(txtTongtien.getText()));
            SimpleDateFormat ngaytt= new SimpleDateFormat("yyyy-MM-dd");
            String date= ngaytt.format(dcNgaythanhtoan.getDate());
            hd.setNgaythanhtoan(date);
            
            hd.setHinhthucthanhtoan(cmbHinhttt.getSelectedItem().toString());
           
            Hoa_donDao dao= new Hoa_donDao();
            dao.insert(hd);
             JOptionPane.showMessageDialog(this, "nhan vien moi da duoc them ");
            }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Error: "+ex.getMessage());
                ex.printStackTrace();
            }
        try {
            showHoadon();
        } catch (SQLException ex) {
            Logger.getLogger(HoaDonJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        // TODO add your handling code here:
        txtMahd.setText("");
        txtMakh.setText("");
        txtManv.setText("");
        txtMadv.setText("");
        txtTongtien.setText("");
        cmbHinhttt.setSelectedIndex(0);
        dcNgaythanhtoan.setDateFormatString("");
    }//GEN-LAST:event_btnLammoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
         StringBuilder sb= new StringBuilder();
        if(txtMahd.getText().equals(""))
        {
            sb.append("Ma hoa don khong duoc de trong!!!");
            txtMahd.setBackground(Color.red);
        }
        else
            txtMahd.setBackground(Color.WHITE);
        if(sb.length()>0)
        {
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        try{
            Hoa_don hd= new Hoa_don();
            hd.setMahd(txtMahd.getText());
            hd.setMakh(txtMakh.getText());
            hd.setManv(txtManv.getText());
            hd.setMadv(txtMadv.getText());
            hd.setTongtien(Float.parseFloat(txtTongtien.getText()));
            SimpleDateFormat ngaytt= new SimpleDateFormat("yyyy-MM-dd");
            String date= ngaytt.format(dcNgaythanhtoan.getDate());
            hd.setNgaythanhtoan(date);
            hd.setHinhthucthanhtoan(cmbHinhttt.getSelectedItem().toString());
           
            Hoa_donDao dao= new Hoa_donDao();
            dao.update(hd);
             JOptionPane.showMessageDialog(this, "nhan vien moi da duoc sua ");
            }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Error: "+ex.getMessage());
                ex.printStackTrace();
            }
        try {
            showHoadon();
        } catch (SQLException ex) {
            Logger.getLogger(HoaDonJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
            if(txtMahd.getText().equals(""))
            {
                sb.append("Ma hoa don khong duoc de trong");
                txtMahd.setBackground(Color.red);
            }else
                txtMahd.setBackground(Color.WHITE);
            if(sb.length()>0)
            {
                JOptionPane.showMessageDialog(this, sb);
                return;
            }
            if(JOptionPane.showConfirmDialog(this, "ban co muon xoa hoa don khong?")==JOptionPane.NO_OPTION)
            {
                return;
            }
            try{
                Hoa_donDao dao= new Hoa_donDao();
                dao.delete(txtMahd.getText());
                
                JOptionPane.showMessageDialog(this, "Hoa don da duoc xoa ");
                btnLammoiActionPerformed(evt);
            }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Error: "+ex.getMessage());
                ex.printStackTrace();
            }
        try {
            showHoadon();
        } catch (SQLException ex) {
            Logger.getLogger(HoaDonJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
         if(txtMahd.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "can nhap ma hoa can tim!!!");
            return;
        }
        
        try{
            Hoa_donDao dao = new Hoa_donDao();
            
            Hoa_don hd = dao.findID(txtMahd.getText());
            
            if(hd !=null)
            {
                txtMakh.setText(hd.getMakh());
                txtManv.setText(hd.getManv());
                txtMadv.setText(hd.getMadv());
                String tt=String.valueOf(hd.getTongtien());
                txtTongtien.setText(tt);
                SimpleDateFormat ngaytt= new SimpleDateFormat("yyyy-MM-dd");
                Date date= ngaytt.parse(hd.getNgaythanhtoan());
                dcNgaythanhtoan.setDate(date);
                cmbHinhttt.setSelectedItem(hd.getHinhthucthanhtoan());
            }else
                JOptionPane.showMessageDialog(this, "khong tim thay ma hoa don!!!");
        }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Error: "+ex.getMessage());
                ex.printStackTrace();
            }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void tabHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabHDMouseClicked
        try {
            // TODO add your handling code here:
            LoadData();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HoaDonJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HoaDonJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(HoaDonJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabHDMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cmbHinhttt;
    private com.toedter.calendar.JDateChooser dcNgaythanhtoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabHD;
    private javax.swing.JTextField txtMadv;
    private javax.swing.JTextField txtMahd;
    private javax.swing.JTextField txtMakh;
    private javax.swing.JTextField txtManv;
    private javax.swing.JTextField txtTongtien;
    // End of variables declaration//GEN-END:variables

    private String DateFormat(java.util.Date date) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
